site_name: "Wet Stuff"

repo_url: "https://github.com/Placeholder-Software/wetsurfacedecals"
repo_name: "GitHub"
edit_uri: ""

google_analytics: ["UA-46722926-4", "wetsurfacedecals.readthedocs.io"]
copyright: "<a href='https://placeholder-software.co.uk/wetstuff/'>Placeholder Software</a>"

markdown_extensions:
    - toc:
        permalink: ÔÉÅ
    - admonition
    - def_list

nav:
- Home: "index.md"
- "Quickstart":
    - "Requirements": "GettingStarted/Requirements.md"
    - "Quick Start": "GettingStarted/QuickStart.md"
    - "Basic Wet Decal": "GettingStarted/WetDecal.md"
    - "Particle Splatter Wet Decals": "GettingStarted/WetParticleSplatter.md"
    - "Weather Integration": "GettingStarted/WeatherIntegration.md"
    - "Compatibility": "GettingStarted/Compatibility.md"
- "Demos":
    - "1. Basic Puddle": "Demo Scenes/Puddle.md"
    - "2. Drying With Timeline": "Demo Scenes/Drying.md"
    - "3. Rain": "Demo Scenes/Rain.md"
    - "4. Particles (Fast Splat)": "Demo Scenes/Particles1.md"
    - "5. Particles (Continuous Drip)": "Demo Scenes/Particles2.md"
    - "6. Triplanar Mapping": "Demo Scenes/Triplanar.md"
#- "Advanced":
#    - "The Rendering Pipeline": "Advanced/RenderingPipeline.md"
#    - "Custom IWetDecal": "Advanced/Implementing_IWetDecal.md"
- "Reference":
    - "ParticleWetSplatter": "Reference/ParticleWetSplatter.md"
    - "ParticleWetSplatterTemplate": "Reference/ParticleWetSplatterTemplate.md"
    - "WetDecal": "Reference/WetDecal.md"
    - "Levels Visualizer": "Reference/LevelsVisualizer.md"
    - "WetStuff": "Reference/WetStuff.md"
    - "BaseExternalWetnessSource": "Reference/BaseExternalWetnessSource.md"
    - "DripLine": "Reference/DripLine.md"
    - "RainPuddle": "Reference/RainPuddle.md"
    - "AutoRainPuddle": "Reference/AutoRainPuddle.md"
    #- "Shaders":
    #    - "WetSurfaceCore": "Reference/Shaders/WetSurfaceCore.md"
    #    - "WetSurfaceMask": "Reference/Shaders/WetSurfaceMask.md"
    #    - "WetSurfaceModifier": "Reference/Shaders/WetSurfaceModifier.md"